import './globals.css'
import { Roboto } from 'next/font/google'

const inter = Roboto({ subsets: ['latin'], weight: ['100', '300', '400', '500', '700', '900'] })

export const metadata = {
  title: 'Ejam | Test Assignement',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-body text-main text-sm xl:text-base select-none`}>{children}</body>
    </html>
  )
}
